name: Build, Test and Distribute
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build
      uses: vgaidarji/android-github-actions-build@v1.0.1
      env:
        FABRIC_API_KEY: ${{ secrets.FABRIC_API_KEY }}
        FABRIC_API_SECRET: ${{ secrets.FABRIC_API_SECRET }}
      with:
        args: "sdkmanager 'platforms;android-31' && ./gradlew assembleDebug -PpreDexEnable=false"
    - name: Check
      uses: vgaidarji/android-github-actions-build@v1.0.1
      env:
        FABRIC_API_KEY: ${{ secrets.FABRIC_API_KEY }}
        FABRIC_API_SECRET: ${{ secrets.FABRIC_API_SECRET }}
      with:
        args: "./gradlew testDebug jacocoTestReport checkstyle pmd jdepend lintDebug buildDashboard -PpreDexEnable=false"
    - name: Distribute
      uses: vgaidarji/android-github-actions-build@v1.0.1
      env:
        FABRIC_API_KEY: ${{ secrets.FABRIC_API_KEY }}
        FABRIC_API_SECRET: ${{ secrets.FABRIC_API_SECRET }}
      with:
        args: "./gradlew crashlyticsUploadDistributionDebug -PpreDexEnable=false"
    - name: Publish Code Coverage
      uses: vgaidarji/android-github-actions-build@v1.0.1
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      with:
        args: "./gradlew coveralls -PpreDexEnable=false"
  androidTest:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        env:
          FABRIC_API_KEY: ${{ secrets.FABRIC_API_KEY }}
          FABRIC_API_SECRET: ${{ secrets.FABRIC_API_SECRET }}
        with:
          api-level: 31
          arch: x86
          disable-animations: true
          script: ./gradlew connectedAndroidTest --stacktrace
